// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuyxexhlylasrnlebuhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1eXhleGhseWxhc3JubGVidWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTUyNzcsImV4cCI6MjA3MDEzMTI3N30.PEROXj65LfH_m9cgi_rJKV093yjSsWlZLkuHSkzrS4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});